-- Create payments table for Stripe subscriptions
CREATE TABLE IF NOT EXISTS public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stripe_session_id TEXT UNIQUE NOT NULL,
  plan TEXT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  currency TEXT NOT NULL DEFAULT 'eur',
  customer_email TEXT,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS idx_payments_stripe_session_id ON public.payments(stripe_session_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON public.payments(status);
CREATE INDEX IF NOT EXISTS idx_payments_created_at ON public.payments(created_at);

-- Add RLS (Row Level Security) policies
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- Allow service role to insert payments (for webhooks)
CREATE POLICY "Allow service role insert" ON public.payments
  FOR INSERT TO service_role
  WITH CHECK (true);

-- Allow authenticated users to view their own payments
CREATE POLICY "Allow users view own payments" ON public.payments
  FOR SELECT TO authenticated
  USING (customer_email = auth.email());

-- Allow service role to update payments (for webhooks)
CREATE POLICY "Allow service role update" ON public.payments
  FOR UPDATE TO service_role
  WITH CHECK (true);

-- Grant permissions
GRANT SELECT, INSERT, UPDATE ON public.payments TO service_role;
GRANT SELECT ON public.payments TO authenticated;
