import { createContext, useContext, useState, type ReactNode } from 'react';

type Language = 'fr' | 'en';

interface Translations {
  [key: string]: string;
}

const translations: Record<Language, Translations> = {
  fr: {
    'hero.subtitle': 'Visionnaire. Entrepreneur. Philanthrope.',
    'hero.cta.discover': 'Découvrir l\'Héritage',
    'hero.cta.store': 'Visiter la Boutique',

    'mkh.title': '',
    'mkh.subtitle': 'Héritage d\'Excellence',
    'mkh.ourMission': 'Notre mission',
    'mkh.missionText': 'Les entreprises de MKH agissent comme catalyseur pour le développement économique, social et culturel des peuples du continent africain. Éclairer, former et accompagner : telle est notre vocation première.',
    'mkh.missionText2': 'Elles participent activement à la mise en œuvre d\'actions et d\'outils d\'édification individuelle et collective, mettant ainsi à disposition un accès à des produits multimédia et des services de promotion de haute qualité qui répondent aux besoins pour le progrès social et la construction d\'une puissance géopolitique africaine.',
    'mkh.mission.title': 'Mission',
    'mkh.mission.desc': 'Les entreprises de MKH agissent comme catalyseur pour le développement économique, social et culturel des peuples du continent africain. Éclairer, former et accompagner : telle est notre vocation première.\n\nElles participent activement à la mise en œuvre d\'actions et d\'outils d\'édification individuelle et collective, mettant ainsi à disposition un accès à des produits multimédia et des services de promotion de haute qualité qui répondent aux besoins pour le progrès social et la construction d\'une puissance géopolitique africaine.',
    'mkh.vision.title': 'Vision',
    'mkh.vision.desc': 'MKH porte la vision d\'une Afrique souveraine, puissante et unie — un continent qui prend en main son destin économique, culturel et géopolitique. À travers ses entreprises multisectorielles, MKH contribue à bâtir les fondations d\'une puissance africaine durable, en valorisant les talents, les ressources et l\'identité des peuples africains.',
    'mkh.values.title': 'Valeurs',
    'mkh.values.desc': 'Excellence : exiger le meilleur de soi-même dans chaque action.\nIntégrité : agir avec honnêteté, transparence et cohérence.\nSolidarité : construire ensemble, partager les succès et surmonter les épreuves.\nPanafricanisme : promouvoir l\'unité, la culture et la dignité africaine comme socle de tout développement.',
    'mkh.portrait.title': 'Portrait',
    'mkh.portrait.name': 'MBOUMA KOHOMM Richard – alias Sayë',
    'mkh.portrait.bio': 'De nationalité camerounaise, ayant reçu une formation en sciences politiques et en journalisme dans les années 70 en France, MBOUMA KOHOMM Richard – alias Sayë (son prénom négro-africain) –, est un homme d\'actions et d\'initiatives multiples. Spécialiste en géopolitique internationale, Il jouit d\'une longue expérience comme journaliste et éditeur. Il avait fondé dans le passé, plusieurs journaux : « Afrique Expansion » (1974), « Afrique Diplomatique » (1980), « Afrique Active » (2003). Fondateur de l\'Institut du Panafricanisme, une ONG de promotion de la Cause panafricaine, de Pan Africa Medias Group, il est Président d\'African Leaders Book, un réseau communautaire des acteurs majeurs qui développent et construisent la future Puissance africaine.',
    'mkh.portrait.bio2': 'L\'exercice depuis 55 ans de son métier de journaliste spécialisé en géopolitique, lui offert l\'occasion de rencontres avec des grands leaders africains comme Julius Nyéréré, Sékou Touré, Agostino Neto, Seni Kountché, Jerry Rawlings, Stokely Carmichael alias Kwamé Touré, leader du mouvement de «Civil Rights Activist». Mais aussi, différents et nombreux Africains de milieux sociaux divers, de Pretoria au Caire, de Dakar à Maputo, de Nairobi à Abidjan, de Bamako à Kinshasa… rencontres qui ont affermi son africanisme militant dont les prémisses commencèrent à germer dès sa prime jeunesse en assistant à Douala aux meetings du grand leader camerounais Ruben Um Nyobè.',
    'mkh.extendedBio': 'Disciple des préceptes du stoïcisme des maîtres Épictète, Marc Aurèle et Sénèque, mais aussi des préceptes ésotériques issus du Ramesseum, Mbouma Kohomm mène depuis plus de 55 ans une œuvre journalistique, littéraire et humaniste au service de l\'Afrique et de ses peuples.',
    'mkh.eternalLove.title': 'Liens d\'Amour éternel',
    'mkh.eternalLove.parents': 'Parents',
    'mkh.eternalLove.parentsLegend': 'Mbouma Podok Nop Pierre – Ngo Banim Ida (légende)',
    'mkh.eternalLove.soulmate': 'Âme-sœur',
    'mkh.eternalLove.soulmateName': 'Ngini Chantal Marie-Christine',
    'mkh.philosophy.title': 'Disciple des préceptes',
    'mkh.philosophy.text': 'Disciple des préceptes du stoïcisme des maîtres Épictète, Marc Aurèle et Sénèque, mais aussi des préceptes ésotériques issus du Ramesseum.',
    'mkh.works.title': 'Auteur de plusieurs ouvrages',
    'mkh.works.list': '« Cameroun : le combat continu » (éd. L\'Harmattan, 2001) · « Cameroun, Afrique : Que faire ? » (éd. Diallo Telli, 2004) · « Kellam la Magnifique » (éd. Liyi Mam, 2012) · « La vie ne meurt pas » (éd. Liyi Mam, 2017) · « Pour un Cameroun Nouveau : le rêve de Ruben Um Nyobè » (éd. Liyi Mam, à paraître). Titulaire de l\'éméritat en journalisme et de la Légion d\'honneur à titre étranger.',
    'mkh.pub.cameroun.title': 'Pour un Cameroun Nouveau',
    'mkh.pub.cameroun.type': 'Essai',
    'mkh.pub.cameroun.year': '2026',
    'mkh.pub.cameroun.desc': 'Le rêve de Ruben Um Nyobè — une réflexion visionnaire sur l\'avenir politique et social du Cameroun, appel au renouveau et à la souveraineté du peuple camerounais.',
    'mkh.pub.alb.title': 'African Leaders Book',
    'mkh.pub.alb.type': 'Guide',
    'mkh.pub.alb.year': '2025',
    'mkh.pub.alb.desc': 'Un réseau communautaire des acteurs majeurs qui développent et construisent la future Puissance africaine. Tribune des actions et visions des leaders du continent.',
    'mkh.pub.pom.title': 'Pôm Man (Fils unique)',
    'mkh.pub.pom.type': 'Mémoires',
    'mkh.pub.pom.year': '2027',
    'mkh.pub.pom.desc': 'Mémoires intimes d\'une vie consacrée à l\'Afrique — de l\'enfance à Douala aux rencontres avec les grands leaders africains, un témoignage unique sur 55 ans de militantisme panafricain.',
    'mkh.pub.pouvoir.title': 'Pouvoir — Hors-série',
    'mkh.pub.pouvoir.type': 'Revue',
    'mkh.pub.pouvoir.year': '2026',
    'mkh.pub.pouvoir.desc': 'Ô Cameroun, chère Patrie ! — Points de vue et explicitations 2018-2025. Une analyse géopolitique approfondie par Sayë (Richard) Mbouma Kohomm.',
    'publications-presse.title': 'Publications Presse',
    'publications-presse.subtitle': 'Presse',
    'publications-presse.tribune.title': 'Tribune Libre',
    'publications-presse.tribune.type': 'Opinion',
    'publications-presse.tribune.year': '2025',
    'publications-presse.tribune.desc': 'Espace d\'expression libre dédié aux analyses géopolitiques et aux réflexions sur l\'actualité africaine et internationale.',
    'publications-presse.revue.title': 'Revue Pouvoir',
    'publications-presse.revue.type': 'Revue',
    'publications-presse.revue.year': '2026',
    'publications-presse.revue.desc': 'Publication périodique analysant les enjeux de pouvoir, de gouvernance et de géopolitique en Afrique et dans le monde.',
    'publications-presse.choose.title': 'Choose Africa',
    'publications-presse.choose.type': 'Magazine',
    'publications-presse.choose.year': '2025',
    'publications-presse.choose.desc': 'Magazine dédié à la promotion des choix stratégiques de l\'Afrique pour son développement autonome et souverain.',
    'mkh.action.title': 'Action Humanitaire',
    'mkh.action.subtitle': 'Engagement',
    'mkh.action.project': 'Projet de création d\'une association d\'aide humanitaire',
    'mkh.action.start': '1er septembre 2026',
    'mkh.action.desc': 'Implantation de 10 000 Maisons citoyennes à Yaoundé, Cameroun.',
    'mkh.spirit.title': 'Esprit libre',
    'mkh.spirit.text': 'Esprit libre, sa vision, sa conviction et son action sont caractérisées par la volonté de toujours tenter, braver, persister, persévérer… D\'être toujours fidèle à soi-même, prendre corps à corps son destin, d\'étonner la catastrophe par le peu de peur qu\'elle fait sur soi, tantôt pour affronter la puissance injuste, tantôt pour insulter la victoire ivre, tenir bon, tenir tête…',
    'mkh.maxime.text': 'Un esprit ressourcé à la lumière qui l\'électrise, qui guide son action. Appliquant cette maxime : la matière se recycle, l\'esprit se ressource.',
    'mkh.stats.years': 'Années d\'expérience',
    'mkh.stats.projects': 'Projets réalisés',
    'mkh.stats.lives': 'Vies impactées',
    'mkh.quote': 'Le succès n\'a de valeur que s\'il est partagé.',

    'impact.title': 'Notre Impact',
    'impact.subtitle': 'Construire une Afrique souveraine et prospère à travers l\'éducation, la santé, l\'entrepreneuriat et l\'action humanitaire.',
    'impact.learnMore': 'En savoir plus',
    'impact.works.education.title': 'Éducation pour Tous',
    'impact.works.education.category': 'Éducation',
    'impact.works.education.desc': 'Construction d\'écoles modernes et de centres de formation à travers le continent africain, offrant un accès à l\'éducation de qualité aux nouvelles générations.',
    'impact.works.health.title': 'Santé Mobile',
    'impact.works.health.category': 'Santé',
    'impact.works.health.desc': 'Déploiement de cliniques mobiles et de programmes de santé préventive pour apporter des soins médicaux aux communautés africaines les plus isolées.',
    'impact.works.entrepreneurship.title': 'Incubateur Jeunes Talents',
    'impact.works.entrepreneurship.category': 'Entrepreneuriat',
    'impact.works.entrepreneurship.desc': 'Formation et financement de jeunes entrepreneurs africains à travers les programmes MKH, contribuant à la création d\'emplois et au développement économique.',
    'impact.publications.title': 'Publications',
    'impact.publications.book1.title': 'Pour un Cameroun Nouveau',
    'impact.publications.book1.type': 'Essai',
    'impact.publications.book1.desc': 'En menant une lutte acharnée pour la Réunification et l\'Indépendance de notre chère Patrie, Ruben UM NYOBE et ses partisans rêvaient d\'un autre avenir pour notre beau et grand pays. C\'est ce rêve visionnaire que l\'auteur a voulu faire partager ici pour éveiller les consciences aux enjeux cruciaux qui conditionnent l\'avenir d\'un Cameroun Nouveau.',
    'impact.publications.book2.title': 'African Leaders Book',
    'impact.publications.book2.type': 'Guide',
    'impact.publications.book2.desc': 'Tribune des actions et visions des leaders africains. Réseau communautaire des acteurs qui construisent la future Puissance africaine.',
    'impact.publications.book3.title': 'Pôm Man (Fils unique)',
    'impact.publications.book3.type': 'Mémoires',
    'impact.publications.book3.desc': '« Tu seras un homme, mon fils ! » — Évoquant le poème de Kipling, ces mémoires intimes retracent 55 ans de militantisme panafricain, de l\'enfance à Douala aux rencontres avec les grands leaders africains, en passant par les épreuves et les victoires d\'une vie consacrée à l\'Afrique et à ses peuples.',
    'impact.publications.book4.title': 'Pouvoir — Hors-série',
    'impact.publications.book4.type': 'Revue',
    'impact.publications.book4.desc': 'Ô Cameroun, chère Patrie ! — Articles publiés entre 2018 et 2025 dans la revue POUVOIR : analyse des grands enjeux du destin camerounais, cohésion nationale, bévues géopolitiques, et propositions pour un avenir radieux. Points de vue engagés et pertinents sur la situation sociopolitique du Cameroun.',
    'impact.humanitarian.title': 'Action Humanitaire',
    'impact.humanitarian.subtitle': 'Engagement Social',
    'impact.humanitarian.project': 'Projet de création d\'une association d\'aide humanitaire',
    'impact.humanitarian.date': '1er septembre 2026',
    'impact.humanitarian.desc': 'Implantation de 10 000 Maisons citoyennes à Yaoundé, Cameroun.',
    'impact.humanitarian.gala1': 'Gala de charité MKH – Paris',
    'impact.humanitarian.gala1date': '15 juin 2027',
    'impact.humanitarian.gala1desc': 'Soirée de donation pour le financement des programmes de lutte contre la pauvreté au Cameroun.',
    'impact.humanitarian.gala2': 'Gala de charité MKH – Yaoundé',
    'impact.humanitarian.gala2date': '30 novembre 2027',
    'impact.humanitarian.gala2desc': 'Gala de charité en faveur des communautés défavorisées du Cameroun.',

    'store.title': 'Le Store MKH',
    'store.subtitle': 'Découvrez notre collection exclusive de produits de luxe africains.',
    'store.fashion.title': 'Fashion',
    'store.fashion.men.title': 'Homme',
    'store.fashion.women.title': 'Femme',
    'store.fashion.men.suit1.name': 'Costume Royal Ébène',
    'store.fashion.men.suit1.desc': 'Costume trois pièces en laine fine avec broderies traditionnelles.',
    'store.fashion.men.suit2.name': 'Ensemble Président',
    'store.fashion.men.suit2.desc': 'Costume élégant aux motifs géométriques africains subtils.',
    'store.fashion.women.dress1.name': 'Robe Reine Mère',
    'store.fashion.women.dress1.desc': 'Robe longue en soie avec imprimés wax authentiques.',
    'store.fashion.women.dress2.name': 'Robe Impérial',
    'store.fashion.women.dress2.desc': 'Création unique mêlant tradition et modernité.',
    'store.atrium.title': 'Atrium',
    'store.atrium.wine': 'Vins',
    'store.atrium.cigars': 'Cigares',
    'store.atrium.coffee': 'Café',
    'store.atrium.spirits': 'Alcools fins',
    'store.atrium.tisane': 'Thérapie',
    'store.atrium.wine1.name': 'Château MKH Rouge',
    'store.atrium.wine1.desc': 'Dégustation — millésime exceptionnel, notes de fruits noirs et d\'épices. De 45 à 65 € la bouteille.',
    'store.atrium.cigars1.name': 'Cigares MKH Premium',
    'store.atrium.cigars1.desc': 'Sélection exclusive de cigares premium. De 222 à 340 € le coffret de 20 unités.',
    'store.atrium.coffee1.name': 'Café Arabica MKH',
    'store.atrium.coffee1.desc': 'Café d\'exception des hauts plateaux africains. 15 € l\'unité.',
    'store.atrium.spirits1.name': 'Whisky Single Malt MKH',
    'store.atrium.spirits1.desc': 'Whisky Single Malt d\'exception. 65 € | Cognac : 125 €.',
    'store.atrium.tisane1.name': 'Tisane Magique MKH',
    'store.atrium.tisane1.desc': 'Booster d\'énergie naturel — mélange de plantes thérapeutiques africaines soigneusement sélectionnées. 35 € le paquet de 20 unités.',
    'store.atrium.tisane1.longDesc': 'La Tisane Magique MKH (BEMA) est un mélange unique de plantes médicinales africaines aux propriétés thérapeutiques exceptionnelles. Elle contribue au renforcement du système immunitaire, améliore la circulation sanguine et procure une énergie vitale durable. élaborée selon des savoirs traditionnels transmis de génération en génération.',
    'store.addToCart': 'Ajouter au panier',

    'news.title': 'Actualités',
    'news.subtitle': 'Restez informé de nos actions et événements à travers le continent.',
    'news.readMore': 'Lire la suite',
    'news.actions.title': 'Action',
    'news.events.title': 'Événement',
    'news.actions.action1.title': 'Lancement du Programme Éducatif MKH',
    'news.actions.action1.desc': 'Inauguration de nouvelles écoles et centres de formation au Cameroun, offrant un accès à l\'éducation de qualité aux communautés rurales.',
    'news.actions.action2.title': 'Campagne de Santé Préventive',
    'news.actions.action2.desc': 'Déploiement de cliniques mobiles et dépistages gratuits pour les communautés défavorisées du Cameroun.',
    'news.events.event1.title': 'Sommet Choose Africa',
    'news.events.event1.desc': 'Rencontre annuelle des leaders économiques, politiques et culturels du continent africain et de la diaspora.',
    'news.events.event2.title': 'Gala de Charité MKH – Yaoundé',
    'news.events.event2.desc': 'Soirée de levée de fonds pour les programmes humanitaires en faveur des communautés défavorisées du Cameroun.',

    'inscription.title': 'Rejoindre l\'Aventure',
    'inscription.subtitle': 'Devenez acteur du changement en rejoignant la communauté MKH.',
    'inscription.actionnariat.title': 'Actionnariat',
    'inscription.actionnariat.heading': 'Devenez Actionnaire',
    'inscription.actionnariat.desc': 'Investissez dans l\'avenir de l\'Afrique et participez à la croissance du Groupe MKH : Multimédias – Formation – Agro-industrie – Immobilier – Transports – Fraternité Spirituelle.',
    'inscription.actionnariat.benefit1': 'Dividendes attractifs',
    'inscription.actionnariat.benefit2': 'Assemblées générales exclusives',
    'inscription.actionnariat.benefit3': 'Accès prioritaire aux événements',
    'inscription.actionnariat.benefit4': 'Rapports financiers trimestriels',
    'inscription.actionnariat.cta': 'Devenir actionnaire',
    'inscription.actionnariat.card.title': 'Rendement Annuel',
    'inscription.actionnariat.card.desc': 'Performance historique de nos actions',
    'inscription.actionnariat.card.return': '9 à 11,5 % rendement moyen',
    'inscription.abonnement.title': 'Abonnement',
    'inscription.abonnement.heading': 'Nos Formules d\'Abonnement',
    'inscription.abonnement.desc': 'Recevez régulièrement nos produits exclusifs et publications.',
    'inscription.abonnement.month': 'mois',
    'inscription.abonnement.popular': 'Populaire',
    'inscription.abonnement.subscribe': 'S\'abonner',
    'inscription.abonnement.basic.name': 'Essentiel',
    'inscription.abonnement.basic.feature1': 'Newsletter mensuelle',
    'inscription.abonnement.basic.feature2': 'Accès aux publications',
    'inscription.abonnement.basic.feature3': '10% de réduction Store',
    'inscription.abonnement.premium.name': 'Premium',
    'inscription.abonnement.premium.feature1': 'Tous les avantages Essentiel',
    'inscription.abonnement.premium.feature2': 'Box trimestrielle',
    'inscription.abonnement.premium.feature3': 'Conseils personnalisés',
    'inscription.abonnement.premium.feature4': '20% de réduction Store',
    'inscription.abonnement.vip.name': 'VIP',
    'inscription.abonnement.vip.feature1': 'Tous les avantages Premium',
    'inscription.abonnement.vip.feature2': 'Box mensuelle exclusive',
    'inscription.abonnement.vip.feature3': 'Accès aux événements privés',
    'inscription.abonnement.vip.feature4': '30% de réduction Store',
    'inscription.abonnement.vip.feature5': 'Rencontre annuelle avec MK',
    'inscription.partenariat.title': 'Partenariat',
    'inscription.partenariat.heading': 'Devenez Partenaire',
    'inscription.partenariat.desc': 'Collaborons ensemble pour créer un impact positif.',
    'inscription.partenariat.type1.title': 'Partenariat Média',
    'inscription.partenariat.type1.desc': 'Collaboration éditoriale et rédactionnelle ; enquêtes et recherche d\'information, diffusion de nos publications et couverture événementielle.',
    'inscription.partenariat.type2.title': 'Partenariat Produit',
    'inscription.partenariat.type2.desc': 'Intégrez vos produits de marque dans notre écosystème de diffusion et de promotion.',
    'inscription.partenariat.type3.title': 'Partenariat Stratégique',
    'inscription.partenariat.type3.desc': 'Collaborations de long terme pour des projets communs : Formation – Expertises – Conseils.',
    'inscription.partenariat.learnMore': 'En savoir plus',
    'inscription.form.title': 'Formulaire d\'inscription',
    'inscription.form.name': 'Nom complet',
    'inscription.form.namePlaceholder': 'Votre nom',
    'inscription.form.email': 'Adresse email',
    'inscription.form.emailPlaceholder': 'votre@email.com',
    'inscription.form.phone': 'Téléphone',
    'inscription.form.phonePlaceholder': '+237 6XX XXX XXX',
    'inscription.form.submit': 'Envoyer ma demande',
    'inscription.form.success': 'Votre demande a été envoyée avec succès !',
    'inscription.form.error': 'Erreur lors de l\'inscription.',
    'inscription.form.alreadySignedIn': 'Vous êtes déjà connecté.',

    'account.title': 'Espace Membre',
    'account.subtitle': 'Accédez à votre espace personnel selon votre profil.',
    'account.client.title': 'Client',
    'account.partenaire.title': 'Partenaire',
    'account.actionnaire.title': 'Actionnaire',
    'account.login.title': 'Connexion',
    'account.login.subtitle': 'Connectez-vous à votre espace',
    'account.login.email': 'Email',
    'account.login.emailPlaceholder': 'votre@email.com',
    'account.login.password': 'Mot de passe',
    'account.login.passwordPlaceholder': '••••••••',
    'account.login.submit': 'Se connecter',
    'account.login.forgot': 'Mot de passe oublié ?',
    'account.login.noAccount': 'Pas encore de compte ?',
    'account.login.register': 'S\'inscrire',
    'account.login.success': 'Connexion réussie !',
    'account.logout': 'Déconnexion',
    'account.logout.success': 'Déconnexion réussie',
    'account.client.orders': 'Commandes',
    'account.client.favorites': 'Favoris',
    'account.client.points': 'Points fidélité',
    'account.client.recentOrders': 'Commandes récentes',
    'account.partenaire.collaborations': 'Collaborations',
    'account.partenaire.revenue': 'Revenus',
    'account.partenaire.products': 'Produits',
    'account.partenaire.performance': 'Performance',
    'account.actionnaire.shares': 'Actions',
    'account.actionnaire.value': 'Valeur',
    'account.actionnaire.dividend': 'Dividende',
    'account.actionnaire.growth': 'Croissance',

    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Nous sommes à votre écoute pour toute question ou collaboration.',
    'contact.info.address.title': 'Adresse',
    'contact.info.phone.title': 'Téléphone',
    'contact.info.email.title': 'Email',
    'contact.info.hours.title': 'Horaires',
    'contact.info.hours.content': 'Lun - Ven: 8h - 18h\nSam: 9h - 13h',
    'contact.social.title': 'Suivez-nous',
    'contact.map.text': 'Nos bureaux au Cameroun, en France et au Royaume-Uni',
    'contact.map.link': 'Voir sur Google Maps',
    'contact.form.title': 'Envoyez-nous un message',
    'contact.form.subtitle': 'Nous vous répondrons dans les plus brefs délais.',
    'contact.form.name': 'Nom',
    'contact.form.namePlaceholder': 'Votre nom complet',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'votre@email.com',
    'contact.form.subject': 'Sujet',
    'contact.form.subjectPlaceholder': 'Objet de votre message',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Votre message...',
    'contact.form.submit': 'Envoyer le message',
    'contact.form.success': 'Votre message a été envoyé avec succès !',
    'contact.service.title': 'Service Annonces',
    'contact.service.subtitle': 'Petites annonces',
    'contact.service.desc': 'Déposez vos annonces pour recrutement, ventes, achats, collaborations ou tout autre besoin. Notre service met en relation les offres et les demandes au sein de notre communauté.',
    'contact.service.cta': 'Déposer une annonce',

    'footer.description': 'MKH – Mbouma Kohomm Holding : Catalyseur du développement économique, social et culturel des peuples d\'Afrique. Éclairer, former et accompagner.',
    'footer.mkh.mission': 'Notre Mission',
    'footer.mkh.portrait': 'Portrait de MK',
    'footer.mkh.history': 'Notre Histoire',
    'footer.impact.works': 'Nos Œuvres',
    'footer.impact.publications': 'Publications',
    'footer.impact.partners': 'Partenaires',
    'footer.store.fashion': 'Fashion',
    'footer.store.atrium': 'Atrium',
    'footer.store.new': 'Nouveautés',
    'footer.legal.privacy': 'Politique de confidentialité',
    'footer.legal.terms': 'Conditions d\'utilisation',
    'footer.legal.cookies': 'Cookies',
    'footer.rights': 'Tous droits réservés.',
  },
  en: {
    'hero.subtitle': 'Visionary. Entrepreneur. Philanthropist.',
    'hero.cta.discover': 'Discover the Legacy',
    'hero.cta.store': 'Visit the Store',

    'mkh.title': '',
    'mkh.subtitle': 'Legacy of Excellence',
    'mkh.ourMission': 'Our mission',
    'mkh.missionText': 'MKH companies act as a catalyst for the economic, social and cultural development of the peoples of the African continent. To enlighten, train and support: such is our primary vocation.',
    'mkh.missionText2': 'They actively participate in the implementation of actions and tools for individual and collective development, thus providing access to multimedia products and high-quality promotion services that meet the needs for social progress and the construction of African geopolitical power.',
    'mkh.mission.title': 'Mission',
    'mkh.mission.desc': 'MKH companies act as a catalyst for the economic, social and cultural development of the peoples of the African continent. To enlighten, train and accompany: this is our primary vocation.\n\nThey actively participate in the implementation of actions and tools for individual and collective development, providing access to multimedia products and high-quality promotional services that meet the needs for social progress and the building of an African geopolitical power.',
    'mkh.vision.title': 'Vision',
    'mkh.vision.desc': 'MKH carries the vision of a sovereign, powerful and united Africa — a continent that takes charge of its economic, cultural and geopolitical destiny. Through its multisectoral companies, MKH contributes to building the foundations of lasting African power, by developing the talents, resources and identity of African peoples.',
    'mkh.values.title': 'Values',
    'mkh.values.desc': 'Excellence: demanding the best of oneself in every action.\nIntegrity: acting with honesty, transparency and consistency.\nSolidarity: building together, sharing successes and overcoming challenges.\nPan-Africanism: promoting African unity, culture and dignity as the foundation of all development.',
    'mkh.portrait.title': 'Portrait',
    'mkh.portrait.name': 'MBOUMA KOHOMM Richard – alias Sayë',
    'mkh.portrait.bio': 'Of Cameroonian nationality, having received training in political science and journalism in the 70s in France, MBOUMA KOHOMM Richard – alias Sayë (his African first name) – is a man of multiple actions and initiatives. Specialist in international geopolitics, he enjoys extensive experience as a journalist and editor. He founded in the past several newspapers: "Afrique Expansion" (1974), "Afrique Diplomatique" (1980), "Afrique Active" (2003). Founder of the Institute of Pan-Africanism, an NGO promoting the Pan-African Cause, of Pan Africa Medias Group, he is President of African Leaders Book, a community network of major players who develop and build the future African Power.',
    'mkh.portrait.bio2': 'The exercise for 55 years of his profession as a journalist specializing in geopolitics has given him the opportunity to meet with great African leaders such as Julius Nyerere, Sekou Toure, Agostinho Neto, Seyni Kountche, Jerry Rawlings, Stokely Carmichael alias Kwame Toure, leader of the "Civil Rights Activist" movement. But also, different and numerous Africans from diverse social backgrounds, from Pretoria to Cairo, from Dakar to Maputo, from Nairobi to Abidjan, from Bamako to Kinshasa... encounters that have strengthened his militant Africanism whose premises began to germinate from his early youth by attending in Douala the meetings of the great Cameroonian leader Ruben Um Nyobe.',
    'mkh.extendedBio': 'A disciple of the precepts of Stoicism from masters Epictetus, Marcus Aurelius and Seneca, and also of the esoteric precepts from the Ramesseum, Mbouma Kohomm has for over 55 years conducted journalistic, literary and humanist work in service of Africa and its peoples.',
    'mkh.eternalLove.title': 'Eternal Love Links',
    'mkh.eternalLove.parents': 'Parents',
    'mkh.eternalLove.parentsLegend': 'Mbouma Podok Nop Pierre – Ngo Banim Ida (legend)',
    'mkh.eternalLove.soulmate': 'Soulmate',
    'mkh.eternalLove.soulmateName': 'Ngini Chantal Marie-Christine',
    'mkh.philosophy.title': 'Disciple of the precepts',
    'mkh.philosophy.text': 'Disciple of the precepts of stoicism from the masters Epictetus, Marcus Aurelius and Seneca, but also of the esoteric precepts from the Ramesseum.',
    'mkh.works.title': 'Author of several works',
    'mkh.works.list': '"Cameroon: the continuing fight" (L\'Harmattan, 2001) · "Cameroon, Africa: What to do?" (Diallo Telli, 2004) · "Kellam the Magnificent" (Liyi Mam, 2012) · "Life does not die" (Liyi Mam, 2017) · "For a New Cameroon: the dream of Ruben Um Nyobe" (Liyi Mam, forthcoming). Holder of emeritus in journalism and the Legion of Honor as a foreigner.',
    'mkh.pub.cameroun.title': 'For a New Cameroon',
    'mkh.pub.cameroun.type': 'Essay',
    'mkh.pub.cameroun.year': '2026',
    'mkh.pub.cameroun.desc': 'The dream of Ruben Um Nyobe — a visionary reflection on the political and social future of Cameroon, a call for renewal and the sovereignty of the Cameroonian people.',
    'mkh.pub.alb.title': 'African Leaders Book',
    'mkh.pub.alb.type': 'Guide',
    'mkh.pub.alb.year': '2025',
    'mkh.pub.alb.desc': 'A community network of key players building the future African Power. A tribune for the actions and visions of African leaders.',
    'mkh.pub.pom.title': 'Pôm Man (Only Child)',
    'mkh.pub.pom.type': 'Memoirs',
    'mkh.pub.pom.year': '2027',
    'mkh.pub.pom.desc': 'Intimate memoirs of a life devoted to Africa — from childhood in Douala to encounters with great African leaders, a unique testimony spanning 55 years of Pan-African activism.',
    'mkh.pub.pouvoir.title': 'Pouvoir — Special Issue',
    'mkh.pub.pouvoir.type': 'Review',
    'mkh.pub.pouvoir.year': '2026',
    'mkh.pub.pouvoir.desc': 'O Cameroon, dear Fatherland! Viewpoints and explanations 2018-2025. In-depth geopolitical analysis by Sayë (Richard) Mbouma Kohomm.',
    'publications-presse.title': 'Press Publications',
    'publications-presse.subtitle': 'Press',
    'publications-presse.tribune.title': 'Free Tribune',
    'publications-presse.tribune.type': 'Opinion',
    'publications-presse.tribune.year': '2025',
    'publications-presse.tribune.desc': 'A space for free expression dedicated to geopolitical analyses and reflections on African and international current affairs.',
    'publications-presse.revue.title': 'Pouvoir Review',
    'publications-presse.revue.type': 'Review',
    'publications-presse.revue.year': '2026',
    'publications-presse.revue.desc': 'Periodic publication analyzing issues of power, governance and geopolitics in Africa and worldwide.',
    'publications-presse.choose.title': 'Choose Africa',
    'publications-presse.choose.type': 'Magazine',
    'publications-presse.choose.year': '2025',
    'publications-presse.choose.desc': 'Magazine dedicated to promoting Africa\'s strategic choices for its autonomous and sovereign development.',
    'mkh.action.title': 'Humanitarian Action',
    'mkh.action.subtitle': 'Commitment',
    'mkh.action.project': 'Project to create a humanitarian aid association',
    'mkh.action.start': 'September 1, 2026',
    'mkh.action.desc': 'Establishment of 10,000 Citizens\' Houses in Yaoundé, Cameroon.',
    'mkh.spirit.title': 'Free spirit',
    'mkh.spirit.text': 'A free spirit: his vision, his conviction and his action are characterized by the will to always try, to brave, to persist, to persevere… To always be faithful to oneself, to seize one\'s destiny, to astonish misfortune by the little fear it inspires, sometimes to face unjust power, sometimes to defy a hollow victory — to hold firm, to hold one\'s ground…',
    'mkh.maxime.text': 'A spirit refreshed in the light that electrifies him, which guides his action. Applying this maxim: matter recycles, spirit is refreshed.',
    'mkh.stats.years': 'Years of experience',
    'mkh.stats.projects': 'Projects completed',
    'mkh.stats.lives': 'Lives impacted',
    'mkh.quote': 'Success only has value if it is shared.',

    'impact.title': 'Our Impact',
    'impact.subtitle': 'Building a sustainable future through education, health, and entrepreneurship.',
    'impact.learnMore': 'Learn more',
    'impact.works.education.title': 'Education for All',
    'impact.works.education.category': 'Education',
    'impact.works.education.desc': 'Construction of 50 modern schools in rural areas, providing access to quality education for over 10,000 children.',
    'impact.works.health.title': 'Mobile Health',
    'impact.works.health.category': 'Health',
    'impact.works.health.desc': 'Deployment of mobile clinics to bring medical care to the most isolated communities.',
    'impact.works.entrepreneurship.title': 'Young Talent Incubator',
    'impact.works.entrepreneurship.category': 'Entrepreneurship',
    'impact.works.entrepreneurship.desc': 'Training and financing of 500 young entrepreneurs, creating over 2,000 direct jobs.',
    'impact.publications.title': 'Publications',
    'impact.publications.book1.title': 'For a New Cameroon',
    'impact.publications.book1.type': 'Essay',
    'impact.publications.book1.desc': 'The dream of Ruben Um Nyobe — a visionary reflection on the future of Cameroon, a call for renewal and sovereignty.',
    'impact.publications.book2.title': 'African Leaders Book',
    'impact.publications.book2.type': 'Guide',
    'impact.publications.book2.desc': 'A tribune for the actions and visions of African leaders. Community network of actors building the future African Power.',
    'impact.publications.book3.title': 'Pôm Man (Only Child)',
    'impact.publications.book3.type': 'Memoirs',
    'impact.publications.book3.desc': 'Memoirs of a life devoted to Africa — from childhood in Douala to encounters with great African leaders over 55 years of activism.',
    'impact.publications.book4.title': 'Pouvoir — Special Issue',
    'impact.publications.book4.type': 'Review',
    'impact.publications.book4.desc': 'O Cameroon, dear Fatherland! Viewpoints and explanations 2018-2025. Geopolitical analysis by Sayë Richard Mbouma Kohomm.',
    'impact.humanitarian.title': 'Humanitarian Action',
    'impact.humanitarian.subtitle': 'Social Commitment',
    'impact.humanitarian.project': 'Project to create a humanitarian aid association',
    'impact.humanitarian.date': 'September 1, 2026',
    'impact.humanitarian.desc': 'Establishment of 10,000 Citizens\' Houses in Yaoundé, Cameroon.',
    'impact.humanitarian.gala1': 'MKH Charity Gala – Paris',
    'impact.humanitarian.gala1date': 'June 15, 2027',
    'impact.humanitarian.gala1desc': 'Fundraising evening for programs to fight poverty in Cameroon.',
    'impact.humanitarian.gala2': 'MKH Charity Gala – Yaoundé',
    'impact.humanitarian.gala2date': 'November 30, 2027',
    'impact.humanitarian.gala2desc': 'Charity gala in favor of underprivileged communities in Cameroon.',

    'store.title': 'The MKH Store',
    'store.subtitle': 'Discover our exclusive collection of exceptional products.',
    'store.fashion.title': 'Fashion',
    'store.fashion.men.title': 'Men',
    'store.fashion.women.title': 'Women',
    'store.fashion.men.suit1.name': 'Royal Ebony Suit',
    'store.fashion.men.suit1.desc': 'Three-piece fine wool suit with traditional embroidery.',
    'store.fashion.men.suit2.name': 'Presidential Ensemble',
    'store.fashion.men.suit2.desc': 'Elegant suit with subtle African geometric patterns.',
    'store.fashion.women.dress1.name': 'Queen Mother Dress',
    'store.fashion.women.dress1.desc': 'Long silk dress with authentic wax prints.',
    'store.fashion.women.dress2.name': 'Imperial Dress',
    'store.fashion.women.dress2.desc': 'Unique creation blending tradition and modernity.',
    'store.atrium.title': 'Atrium',
    'store.atrium.wine': 'Wines',
    'store.atrium.cigars': 'Cigars',
    'store.atrium.coffee': 'Coffee',
    'store.atrium.spirits': 'Fine Spirits',
    'store.atrium.tisane': 'Therapy',
    'store.atrium.wine1.name': 'Château MKH Red',
    'store.atrium.wine1.desc': 'Tasting — exceptional vintage, notes of black fruits and spices. From €45 to €65 per bottle.',
    'store.atrium.cigars1.name': 'MKH Premium Cigars',
    'store.atrium.cigars1.desc': 'Exclusive selection of premium cigars. From €222 to €340 per box of 20.',
    'store.atrium.coffee1.name': 'MKH Arabica Coffee',
    'store.atrium.coffee1.desc': 'Exceptional coffee from the African highlands. €15 per unit.',
    'store.atrium.spirits1.name': 'MKH Single Malt Whisky',
    'store.atrium.spirits1.desc': 'Exceptional Single Malt Whisky. €65 | Cognac: €125.',
    'store.atrium.tisane1.name': 'MKH Magic Herbal Tea',
    'store.atrium.tisane1.desc': 'Natural energy booster — blend of carefully selected African therapeutic plants. €35 per pack of 20.',
    'store.atrium.tisane1.longDesc': 'The MKH Magic Herbal Tea (BEMA) is a unique blend of African medicinal plants with exceptional therapeutic properties. It helps strengthen the immune system, improves blood circulation and provides lasting vital energy. Developed according to traditional knowledge passed down from generation to generation.',
    'store.addToCart': 'Add to cart',

    'news.title': 'News',
    'news.subtitle': 'Stay informed about our actions and events across the continent.',
    'news.readMore': 'Read more',
    'news.actions.title': 'Action',
    'news.events.title': 'Event',
    'news.actions.action1.title': 'Launch of the MKH Educational Program',
    'news.actions.action1.desc': 'Opening of new schools and training centres in Cameroon, providing quality education access to rural communities.',
    'news.actions.action2.title': 'Preventive Health Campaign',
    'news.actions.action2.desc': 'Deployment of mobile clinics and free screenings for underprivileged communities in Cameroon.',
    'news.events.event1.title': 'Sommet Choose Africa',
    'news.events.event1.desc': 'Annual gathering of economic, political and cultural leaders from across the African continent and diaspora.',
    'news.events.event2.title': 'MKH Charity Gala – Yaoundé',
    'news.events.event2.desc': 'Fundraising evening for humanitarian programs benefiting underprivileged communities in Cameroon.',

    'inscription.title': 'Join the Adventure',
    'inscription.subtitle': 'Become an actor of change by joining the MKH community.',
    'inscription.actionnariat.title': 'Shareholding',
    'inscription.actionnariat.heading': 'Become a Shareholder',
    'inscription.actionnariat.desc': 'Invest in Africa\'s future and participate in the growth of the MKH Group: Multimedia – Training – Agro-industry – Real Estate – Transport – Spiritual Brotherhood.',
    'inscription.actionnariat.benefit1': 'Attractive dividends',
    'inscription.actionnariat.benefit2': 'Exclusive general meetings',
    'inscription.actionnariat.benefit3': 'Priority access to events',
    'inscription.actionnariat.benefit4': 'Quarterly financial reports',
    'inscription.actionnariat.cta': 'Become a shareholder',
    'inscription.actionnariat.card.title': 'Annual Return',
    'inscription.actionnariat.card.desc': 'Historical performance of our shares',
    'inscription.actionnariat.card.return': '9 to 11.5% average return',
    'inscription.abonnement.title': 'Subscription',
    'inscription.abonnement.heading': 'Our Subscription Plans',
    'inscription.abonnement.desc': 'Regularly receive our exclusive products and publications.',
    'inscription.abonnement.month': 'month',
    'inscription.abonnement.popular': 'Popular',
    'inscription.abonnement.subscribe': 'Subscribe',
    'inscription.abonnement.basic.name': 'Essential',
    'inscription.abonnement.basic.feature1': 'Monthly newsletter',
    'inscription.abonnement.basic.feature2': 'Access to publications',
    'inscription.abonnement.basic.feature3': '10% Store discount',
    'inscription.abonnement.premium.name': 'Premium',
    'inscription.abonnement.premium.feature1': 'All Essential benefits',
    'inscription.abonnement.premium.feature2': 'Quarterly box',
    'inscription.abonnement.premium.feature3': 'Personalized advice',
    'inscription.abonnement.premium.feature4': '20% Store discount',
    'inscription.abonnement.vip.name': 'VIP',
    'inscription.abonnement.vip.feature1': 'All Premium benefits',
    'inscription.abonnement.vip.feature2': 'Exclusive monthly box',
    'inscription.abonnement.vip.feature3': 'Access to private events',
    'inscription.abonnement.vip.feature4': '30% Store discount',
    'inscription.abonnement.vip.feature5': 'Annual meeting with MK',
    'inscription.partenariat.title': 'Partnership',
    'inscription.partenariat.heading': 'Become a Partner',
    'inscription.partenariat.desc': 'Let\'s work together to create positive impact.',
    'inscription.partenariat.type1.title': 'Media Partnership',
    'inscription.partenariat.type1.desc': 'Editorial and editorial collaboration; investigations and information research, distribution of our publications and event coverage.',
    'inscription.partenariat.type2.title': 'Product Partnership',
    'inscription.partenariat.type2.desc': 'Integrate your branded products into our distribution and promotion ecosystem.',
    'inscription.partenariat.type3.title': 'Strategic Partnership',
    'inscription.partenariat.type3.desc': 'Long-term collaborations for joint projects: Training – Expertise – Consulting.',
    'inscription.partenariat.learnMore': 'Learn more',
    'inscription.form.title': 'Registration Form',
    'inscription.form.name': 'Full name',
    'inscription.form.namePlaceholder': 'Your name',
    'inscription.form.email': 'Email address',
    'inscription.form.emailPlaceholder': 'your@email.com',
    'inscription.form.phone': 'Phone',
    'inscription.form.phonePlaceholder': '+237 6XX XXX XXX',
    'inscription.form.submit': 'Send my request',
    'inscription.form.success': 'Your request has been sent successfully!',

    'account.title': 'Member Space',
    'account.subtitle': 'Access your personal space according to your profile.',
    'account.client.title': 'Client',
    'account.partenaire.title': 'Partner',
    'account.actionnaire.title': 'Shareholder',
    'account.login.title': 'Login',
    'account.login.subtitle': 'Connect to your space',
    'account.login.email': 'Email',
    'account.login.emailPlaceholder': 'your@email.com',
    'account.login.password': 'Password',
    'account.login.passwordPlaceholder': '••••••••',
    'account.login.submit': 'Login',
    'account.login.forgot': 'Forgot password?',
    'account.login.noAccount': 'Don\'t have an account?',
    'account.login.register': 'Register',
    'account.login.success': 'Login successful!',
    'account.logout': 'Logout',
    'account.logout.success': 'Logout successful',
    'account.client.orders': 'Orders',
    'account.client.favorites': 'Favorites',
    'account.client.points': 'Loyalty points',
    'account.client.recentOrders': 'Recent orders',
    'account.partenaire.collaborations': 'Collaborations',
    'account.partenaire.revenue': 'Revenue',
    'account.partenaire.products': 'Products',
    'account.partenaire.performance': 'Performance',
    'account.actionnaire.shares': 'Shares',
    'account.actionnaire.value': 'Value',
    'account.actionnaire.dividend': 'Dividend',
    'account.actionnaire.growth': 'Growth',

    'contact.title': 'Contact Us',
    'contact.subtitle': 'We are here to listen to any questions or collaboration opportunities.',
    'contact.info.address.title': 'Address',
    'contact.info.phone.title': 'Phone',
    'contact.info.email.title': 'Email',
    'contact.info.hours.title': 'Hours',
    'contact.info.hours.content': 'Mon - Fri: 8am - 6pm\nSat: 9am - 1pm',
    'contact.social.title': 'Follow us',
    'contact.map.text': 'Our offices in Cameroon, France and the United Kingdom',
    'contact.map.link': 'View on Google Maps',
    'contact.form.title': 'Send us a message',
    'contact.form.subtitle': 'We will respond as soon as possible.',
    'contact.form.name': 'Name',
    'contact.form.namePlaceholder': 'Your full name',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'your@email.com',
    'contact.form.subject': 'Subject',
    'contact.form.subjectPlaceholder': 'Subject of your message',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Your message...',
    'contact.form.submit': 'Send message',
    'contact.form.success': 'Your message has been sent successfully!',
    'contact.service.title': 'Classifieds Service',
    'contact.service.subtitle': 'Classified ads',
    'contact.service.desc': 'Post your ads for recruitment, sales, purchases, collaborations or any other needs. Our service connects offers and requests within our community.',
    'contact.service.cta': 'Post an ad',

    'footer.description': 'MKH – Mbouma Kohomm Holding: Catalyst for the economic, social and cultural development of African peoples. To enlighten, train and accompany.',
    'footer.mkh.mission': 'Our Mission',
    'footer.mkh.portrait': 'Portrait of MK',
    'footer.mkh.history': 'Our History',
    'footer.impact.works': 'Our Works',
    'footer.impact.publications': 'Publications',
    'footer.impact.partners': 'Partners',
    'footer.store.fashion': 'Fashion',
    'footer.store.atrium': 'Atrium',
    'footer.store.new': 'New Arrivals',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.legal.terms': 'Terms of Use',
    'footer.legal.cookies': 'Cookies',
    'footer.rights': 'All rights reserved.',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
