import { createContext, useContext, useState, type ReactNode } from 'react';

type Language = 'fr' | 'en';

interface Translations {
  [key: string]: string;
}

const translations: Record<Language, Translations> = {
  fr: {
    'hero.subtitle': 'Visionnaire. Entrepreneur. Philanthrope.',
    'hero.cta.discover': 'Découvrir l\'Héritage',
    'hero.cta.store': 'Visiter la Boutique',

    'mkh.title': 'Notre Histoire',
    'mkh.ourMission': 'Notre Mission',
    'mkh.missionText': 'Transformer l\'Afrique par l\'entrepreneuriat et l\'éducation. Nous croyons en un avenir où chaque Africain a les moyens de réaliser son potentiel et de contribuer au développement de son continent.',
    'mkh.missionText2': 'À travers nos initiatives, nous créons des opportunités, soutenons l\'innovation locale et bâtissons des ponts entre l\'Afrique et le reste du monde.',
    'mkh.mission.title': 'Mission',
    'mkh.mission.desc': 'Transformer l\'Afrique',
    'mkh.vision.title': 'Vision',
    'mkh.vision.desc': 'Un avenir prospère',
    'mkh.values.title': 'Valeurs',
    'mkh.values.desc': 'Excellence et intégrité',
    'mkh.portrait.title': 'Portrait de MK',
    'mkh.portrait.name': 'Mbouma Kohomm',
    'mkh.portrait.bio': 'Entrepreneur visionnaire et philanthrope, Mbouma Kohomm a consacré sa vie à la transformation de l\'Afrique. Fondateur du Groupe MKH, il a bâti un empire qui touche des milliers de vies à travers le continent.',
    'mkh.portrait.bio2': 'Sa vision d\'une Afrique prospère et unie guide chacune de ses actions, des investissements économiques aux initiatives sociales.',
    'mkh.stats.years': 'Années d\'expérience',
    'mkh.stats.projects': 'Projets réalisés',
    'mkh.stats.lives': 'Vies impactées',
    'mkh.quote': 'Le succès n\'a de valeur que s\'il est partagé.',

    'impact.title': 'Notre Impact',
    'impact.subtitle': 'Construire un avenir durable à travers l\'éducation, la santé et l\'entrepreneuriat.',
    'impact.learnMore': 'En savoir plus',
    'impact.works.education.title': 'Éducation pour Tous',
    'impact.works.education.category': 'Éducation',
    'impact.works.education.desc': 'Construction de 50 écoles modernes dans les zones rurales, offrant un accès à l\'éducation de qualité à plus de 10 000 enfants.',
    'impact.works.health.title': 'Santé Mobile',
    'impact.works.health.category': 'Santé',
    'impact.works.health.desc': 'Déploiement de cliniques mobiles pour apporter des soins médicaux aux communautés les plus isolées.',
    'impact.works.entrepreneurship.title': 'Incubateur Jeunes Talents',
    'impact.works.entrepreneurship.category': 'Entrepreneuriat',
    'impact.works.entrepreneurship.desc': 'Formation et financement de 500 jeunes entrepreneurs, créant plus de 2 000 emplois directs.',
    'impact.publications.title': 'Publications',
    'impact.publications.book1.title': 'L\'Afrique de Demain',
    'impact.publications.book1.type': 'Essai',
    'impact.publications.book2.title': 'Entreprendre en Afrique',
    'impact.publications.book2.type': 'Guide',
    'impact.publications.book3.title': 'Le Pouvoir de l\'Unité',
    'impact.publications.book3.type': 'Mémoires',

    'store.title': 'Le Store MKH',
    'store.subtitle': 'Découvrez notre collection exclusive de produits de luxe africains.',
    'store.fashion.title': 'Fashion',
    'store.fashion.men.title': 'Homme',
    'store.fashion.women.title': 'Femme',
    'store.fashion.men.suit1.name': 'Costume Royal Ébène',
    'store.fashion.men.suit1.desc': 'Costume trois pièces en laine fine avec broderies traditionnelles.',
    'store.fashion.men.suit2.name': 'Ensemble Président',
    'store.fashion.men.suit2.desc': 'Costume élégant aux motifs géométriques africains subtils.',
    'store.fashion.women.dress1.name': 'Robe Reine Mère',
    'store.fashion.women.dress1.desc': 'Robe longue en soie avec imprimés wax authentiques.',
    'store.fashion.women.dress2.name': 'Robe Impérial',
    'store.fashion.women.dress2.desc': 'Création unique mêlant tradition et modernité.',
    'store.atrium.title': 'Atrium',
    'store.atrium.wine': 'Vins',
    'store.atrium.cigars': 'Cigares',
    'store.atrium.coffee': 'Café',
    'store.atrium.wine1.name': 'Château MKH Rouge',
    'store.atrium.wine1.desc': 'Millésime exceptionnel, notes de fruits noirs et d\'épices.',
    'store.atrium.cigars1.name': 'Cigares MKH Premium',
    'store.atrium.cigars1.desc': 'Sélection exclusive de cigares dominicains.',
    'store.atrium.coffee1.name': 'Café Arabica MKH',
    'store.atrium.coffee1.desc': 'Café d\'exception des hauts plateaux éthiopiens.',
    'store.atrium.spirits1.name': 'Whisky MKH Reserve',
    'store.atrium.spirits1.desc': 'Blend rare vieilli 18 ans en fûts de chêne.',
    'store.addToCart': 'Ajouter au panier',

    'news.title': 'Actualités',
    'news.subtitle': 'Restez informé de nos actions et événements à travers le continent.',
    'news.readMore': 'Lire la suite',
    'news.actions.title': 'Action',
    'news.events.title': 'Événement',
    'news.actions.action1.title': 'Lancement du Programme Éducatif 2025',
    'news.actions.action1.desc': 'Inauguration de 10 nouvelles écoles dans la région de l\'Estuaire.',
    'news.actions.action2.title': 'Campagne de Santé Preventive',
    'news.actions.action2.desc': 'Plus de 5 000 personnes bénéficient de dépistages gratuits.',
    'news.events.event1.title': 'Sommet des Entrepreneurs Africains',
    'news.events.event1.desc': 'Rencontre annuelle des leaders économiques du continent.',
    'news.events.event2.title': 'Gala de Charité MKH',
    'news.events.event2.desc': 'Soirée de levée de fonds pour les programmes éducatifs.',

    'inscription.title': 'Rejoindre l\'Aventure',
    'inscription.subtitle': 'Devenez acteur du changement en rejoignant la communauté MKH.',
    'inscription.actionnariat.title': 'Actionnariat',
    'inscription.actionnariat.heading': 'Devenez Actionnaire',
    'inscription.actionnariat.desc': 'Investissez dans l\'avenir de l\'Afrique et participez à la croissance du Groupe MKH.',
    'inscription.actionnariat.benefit1': 'Dividendes attractifs',
    'inscription.actionnariat.benefit2': 'Assemblées générales exclusives',
    'inscription.actionnariat.benefit3': 'Accès prioritaire aux événements',
    'inscription.actionnariat.benefit4': 'Rapports financiers trimestriels',
    'inscription.actionnariat.cta': 'Devenir actionnaire',
    'inscription.actionnariat.card.title': 'Rendement Annuel',
    'inscription.actionnariat.card.desc': 'Performance historique de nos actions',
    'inscription.actionnariat.card.return': 'rendement moyen',
    'inscription.abonnement.title': 'Abonnement',
    'inscription.abonnement.heading': 'Nos Formules d\'Abonnement',
    'inscription.abonnement.desc': 'Recevez régulièrement nos produits exclusifs et publications.',
    'inscription.abonnement.month': 'mois',
    'inscription.abonnement.popular': 'Populaire',
    'inscription.abonnement.subscribe': 'S\'abonner',
    'inscription.abonnement.basic.name': 'Essentiel',
    'inscription.abonnement.basic.feature1': 'Newsletter mensuelle',
    'inscription.abonnement.basic.feature2': 'Accès aux publications',
    'inscription.abonnement.basic.feature3': '10% de réduction Store',
    'inscription.abonnement.premium.name': 'Premium',
    'inscription.abonnement.premium.feature1': 'Tous les avantages Essentiel',
    'inscription.abonnement.premium.feature2': 'Box trimestrielle',
    'inscription.abonnement.premium.feature3': 'Conseils personnalisés',
    'inscription.abonnement.premium.feature4': '20% de réduction Store',
    'inscription.abonnement.vip.name': 'VIP',
    'inscription.abonnement.vip.feature1': 'Tous les avantages Premium',
    'inscription.abonnement.vip.feature2': 'Box mensuelle exclusive',
    'inscription.abonnement.vip.feature3': 'Accès aux événements privés',
    'inscription.abonnement.vip.feature4': '30% de réduction Store',
    'inscription.abonnement.vip.feature5': 'Rencontre annuelle avec MK',
    'inscription.partenariat.title': 'Partenariat',
    'inscription.partenariat.heading': 'Devenez Partenaire',
    'inscription.partenariat.desc': 'Collaborons ensemble pour créer un impact positif.',
    'inscription.partenariat.type1.title': 'Partenariat Média',
    'inscription.partenariat.type1.desc': 'Diffusion de nos contenus et couverture événementielle.',
    'inscription.partenariat.type2.title': 'Partenariat Produit',
    'inscription.partenariat.type2.desc': 'Intégrez vos produits dans notre écosystème.',
    'inscription.partenariat.type3.title': 'Partenariat Stratégique',
    'inscription.partenariat.type3.desc': 'Collaborations de long terme pour des projets communs.',
    'inscription.partenariat.learnMore': 'En savoir plus',
    'inscription.form.title': 'Formulaire d\'inscription',
    'inscription.form.name': 'Nom complet',
    'inscription.form.namePlaceholder': 'Votre nom',
    'inscription.form.email': 'Adresse email',
    'inscription.form.emailPlaceholder': 'votre@email.com',
    'inscription.form.phone': 'Téléphone',
    'inscription.form.phonePlaceholder': '+241 77 12 34 56',
    'inscription.form.submit': 'Envoyer ma demande',
    'inscription.form.success': 'Votre demande a été envoyée avec succès !',

    'account.title': 'Espace Membre',
    'account.subtitle': 'Accédez à votre espace personnel selon votre profil.',
    'account.client.title': 'Client',
    'account.partenaire.title': 'Partenaire',
    'account.actionnaire.title': 'Actionnaire',
    'account.login.title': 'Connexion',
    'account.login.subtitle': 'Connectez-vous à votre espace',
    'account.login.email': 'Email',
    'account.login.emailPlaceholder': 'votre@email.com',
    'account.login.password': 'Mot de passe',
    'account.login.passwordPlaceholder': '••••••••',
    'account.login.submit': 'Se connecter',
    'account.login.forgot': 'Mot de passe oublié ?',
    'account.login.noAccount': 'Pas encore de compte ?',
    'account.login.register': 'S\'inscrire',
    'account.login.success': 'Connexion réussie !',
    'account.logout': 'Déconnexion',
    'account.logout.success': 'Déconnexion réussie',
    'account.client.orders': 'Commandes',
    'account.client.favorites': 'Favoris',
    'account.client.points': 'Points fidélité',
    'account.client.recentOrders': 'Commandes récentes',
    'account.partenaire.collaborations': 'Collaborations',
    'account.partenaire.revenue': 'Revenus',
    'account.partenaire.products': 'Produits',
    'account.partenaire.performance': 'Performance',
    'account.actionnaire.shares': 'Actions',
    'account.actionnaire.value': 'Valeur',
    'account.actionnaire.dividend': 'Dividende',
    'account.actionnaire.growth': 'Croissance',

    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Nous sommes à votre écoute pour toute question ou collaboration.',
    'contact.info.address.title': 'Adresse',
    'contact.info.phone.title': 'Téléphone',
    'contact.info.email.title': 'Email',
    'contact.info.hours.title': 'Horaires',
    'contact.info.hours.content': 'Lun - Ven: 8h - 18h\nSam: 9h - 13h',
    'contact.social.title': 'Suivez-nous',
    'contact.map.text': 'Retrouvez-nous au cœur de Libreville',
    'contact.map.link': 'Voir sur Google Maps',
    'contact.form.title': 'Envoyez-nous un message',
    'contact.form.subtitle': 'Nous vous répondrons dans les plus brefs délais.',
    'contact.form.name': 'Nom',
    'contact.form.namePlaceholder': 'Votre nom complet',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'votre@email.com',
    'contact.form.subject': 'Sujet',
    'contact.form.subjectPlaceholder': 'Objet de votre message',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Votre message...',
    'contact.form.submit': 'Envoyer le message',
    'contact.form.success': 'Votre message a été envoyé avec succès !',

    'footer.description': 'MKH - Mbouma Kohomm : Transformons l\'Afrique ensemble par l\'entrepreneuriat, l\'éducation et l\'excellence.',
    'footer.mkh.mission': 'Notre Mission',
    'footer.mkh.portrait': 'Portrait de MK',
    'footer.mkh.history': 'Notre Histoire',
    'footer.impact.works': 'Nos Œuvres',
    'footer.impact.publications': 'Publications',
    'footer.impact.partners': 'Partenaires',
    'footer.store.fashion': 'Fashion',
    'footer.store.atrium': 'Atrium',
    'footer.store.new': 'Nouveautés',
    'footer.legal.privacy': 'Politique de confidentialité',
    'footer.legal.terms': 'Conditions d\'utilisation',
    'footer.legal.cookies': 'Cookies',
    'footer.rights': 'Tous droits réservés.',
  },
  en: {
    'hero.subtitle': 'Visionary. Entrepreneur. Philanthropist.',
    'hero.cta.discover': 'Discover the Legacy',
    'hero.cta.store': 'Visit the Store',

    'mkh.title': 'Our Story',
    'mkh.ourMission': 'Our Mission',
    'mkh.missionText': 'Transforming Africa through entrepreneurship and education. We believe in a future where every African has the means to realize their potential and contribute to the development of their continent.',
    'mkh.missionText2': 'Through our initiatives, we create opportunities, support local innovation, and build bridges between Africa and the rest of the world.',
    'mkh.mission.title': 'Mission',
    'mkh.mission.desc': 'Transform Africa',
    'mkh.vision.title': 'Vision',
    'mkh.vision.desc': 'A prosperous future',
    'mkh.values.title': 'Values',
    'mkh.values.desc': 'Excellence and integrity',
    'mkh.portrait.title': 'Portrait of MK',
    'mkh.portrait.name': 'Mbouma Kohomm',
    'mkh.portrait.bio': 'Visionary entrepreneur and philanthropist, Mbouma Kohomm has dedicated his life to transforming Africa. Founder of the MKH Group, he has built an empire that touches thousands of lives across the continent.',
    'mkh.portrait.bio2': 'His vision of a prosperous and united Africa guides each of his actions, from economic investments to social initiatives.',
    'mkh.stats.years': 'Years of experience',
    'mkh.stats.projects': 'Projects completed',
    'mkh.stats.lives': 'Lives impacted',
    'mkh.quote': 'Success only has value if it is shared.',

    'impact.title': 'Our Impact',
    'impact.subtitle': 'Building a sustainable future through education, health, and entrepreneurship.',
    'impact.learnMore': 'Learn more',
    'impact.works.education.title': 'Education for All',
    'impact.works.education.category': 'Education',
    'impact.works.education.desc': 'Construction of 50 modern schools in rural areas, providing access to quality education for over 10,000 children.',
    'impact.works.health.title': 'Mobile Health',
    'impact.works.health.category': 'Health',
    'impact.works.health.desc': 'Deployment of mobile clinics to bring medical care to the most isolated communities.',
    'impact.works.entrepreneurship.title': 'Young Talent Incubator',
    'impact.works.entrepreneurship.category': 'Entrepreneurship',
    'impact.works.entrepreneurship.desc': 'Training and financing of 500 young entrepreneurs, creating over 2,000 direct jobs.',
    'impact.publications.title': 'Publications',
    'impact.publications.book1.title': 'Africa of Tomorrow',
    'impact.publications.book1.type': 'Essay',
    'impact.publications.book2.title': 'Entrepreneurship in Africa',
    'impact.publications.book2.type': 'Guide',
    'impact.publications.book3.title': 'The Power of Unity',
    'impact.publications.book3.type': 'Memoirs',

    'store.title': 'The MKH Store',
    'store.subtitle': 'Discover our exclusive collection of African luxury products.',
    'store.fashion.title': 'Fashion',
    'store.fashion.men.title': 'Men',
    'store.fashion.women.title': 'Women',
    'store.fashion.men.suit1.name': 'Royal Ebony Suit',
    'store.fashion.men.suit1.desc': 'Three-piece fine wool suit with traditional embroidery.',
    'store.fashion.men.suit2.name': 'Presidential Ensemble',
    'store.fashion.men.suit2.desc': 'Elegant suit with subtle African geometric patterns.',
    'store.fashion.women.dress1.name': 'Queen Mother Dress',
    'store.fashion.women.dress1.desc': 'Long silk dress with authentic wax prints.',
    'store.fashion.women.dress2.name': 'Imperial Dress',
    'store.fashion.women.dress2.desc': 'Unique creation blending tradition and modernity.',
    'store.atrium.title': 'Atrium',
    'store.atrium.wine': 'Wines',
    'store.atrium.cigars': 'Cigars',
    'store.atrium.coffee': 'Coffee',
    'store.atrium.wine1.name': 'Château MKH Red',
    'store.atrium.wine1.desc': 'Exceptional vintage, notes of black fruits and spices.',
    'store.atrium.cigars1.name': 'MKH Premium Cigars',
    'store.atrium.cigars1.desc': 'Exclusive selection of Dominican cigars.',
    'store.atrium.coffee1.name': 'MKH Arabica Coffee',
    'store.atrium.coffee1.desc': 'Exceptional coffee from the Ethiopian highlands.',
    'store.atrium.spirits1.name': 'MKH Reserve Whisky',
    'store.atrium.spirits1.desc': 'Rare blend aged 18 years in oak casks.',
    'store.addToCart': 'Add to cart',

    'news.title': 'News',
    'news.subtitle': 'Stay informed about our actions and events across the continent.',
    'news.readMore': 'Read more',
    'news.actions.title': 'Action',
    'news.events.title': 'Event',
    'news.actions.action1.title': 'Launch of the 2025 Educational Program',
    'news.actions.action1.desc': 'Inauguration of 10 new schools in the Estuaire region.',
    'news.actions.action2.title': 'Preventive Health Campaign',
    'news.actions.action2.desc': 'Over 5,000 people benefit from free screenings.',
    'news.events.event1.title': 'African Entrepreneurs Summit',
    'news.events.event1.desc': 'Annual meeting of the continent\'s economic leaders.',
    'news.events.event2.title': 'MKH Charity Gala',
    'news.events.event2.desc': 'Fundraising evening for educational programs.',

    'inscription.title': 'Join the Adventure',
    'inscription.subtitle': 'Become an actor of change by joining the MKH community.',
    'inscription.actionnariat.title': 'Shareholding',
    'inscription.actionnariat.heading': 'Become a Shareholder',
    'inscription.actionnariat.desc': 'Invest in Africa\'s future and participate in the growth of the MKH Group.',
    'inscription.actionnariat.benefit1': 'Attractive dividends',
    'inscription.actionnariat.benefit2': 'Exclusive general meetings',
    'inscription.actionnariat.benefit3': 'Priority access to events',
    'inscription.actionnariat.benefit4': 'Quarterly financial reports',
    'inscription.actionnariat.cta': 'Become a shareholder',
    'inscription.actionnariat.card.title': 'Annual Return',
    'inscription.actionnariat.card.desc': 'Historical performance of our shares',
    'inscription.actionnariat.card.return': 'average return',
    'inscription.abonnement.title': 'Subscription',
    'inscription.abonnement.heading': 'Our Subscription Plans',
    'inscription.abonnement.desc': 'Regularly receive our exclusive products and publications.',
    'inscription.abonnement.month': 'month',
    'inscription.abonnement.popular': 'Popular',
    'inscription.abonnement.subscribe': 'Subscribe',
    'inscription.abonnement.basic.name': 'Essential',
    'inscription.abonnement.basic.feature1': 'Monthly newsletter',
    'inscription.abonnement.basic.feature2': 'Access to publications',
    'inscription.abonnement.basic.feature3': '10% Store discount',
    'inscription.abonnement.premium.name': 'Premium',
    'inscription.abonnement.premium.feature1': 'All Essential benefits',
    'inscription.abonnement.premium.feature2': 'Quarterly box',
    'inscription.abonnement.premium.feature3': 'Personalized advice',
    'inscription.abonnement.premium.feature4': '20% Store discount',
    'inscription.abonnement.vip.name': 'VIP',
    'inscription.abonnement.vip.feature1': 'All Premium benefits',
    'inscription.abonnement.vip.feature2': 'Exclusive monthly box',
    'inscription.abonnement.vip.feature3': 'Access to private events',
    'inscription.abonnement.vip.feature4': '30% Store discount',
    'inscription.abonnement.vip.feature5': 'Annual meeting with MK',
    'inscription.partenariat.title': 'Partnership',
    'inscription.partenariat.heading': 'Become a Partner',
    'inscription.partenariat.desc': 'Let\'s work together to create positive impact.',
    'inscription.partenariat.type1.title': 'Media Partnership',
    'inscription.partenariat.type1.desc': 'Distribution of our content and event coverage.',
    'inscription.partenariat.type2.title': 'Product Partnership',
    'inscription.partenariat.type2.desc': 'Integrate your products into our ecosystem.',
    'inscription.partenariat.type3.title': 'Strategic Partnership',
    'inscription.partenariat.type3.desc': 'Long-term collaborations for joint projects.',
    'inscription.partenariat.learnMore': 'Learn more',
    'inscription.form.title': 'Registration Form',
    'inscription.form.name': 'Full name',
    'inscription.form.namePlaceholder': 'Your name',
    'inscription.form.email': 'Email address',
    'inscription.form.emailPlaceholder': 'your@email.com',
    'inscription.form.phone': 'Phone',
    'inscription.form.phonePlaceholder': '+241 77 12 34 56',
    'inscription.form.submit': 'Send my request',
    'inscription.form.success': 'Your request has been sent successfully!',

    'account.title': 'Member Space',
    'account.subtitle': 'Access your personal space according to your profile.',
    'account.client.title': 'Client',
    'account.partenaire.title': 'Partner',
    'account.actionnaire.title': 'Shareholder',
    'account.login.title': 'Login',
    'account.login.subtitle': 'Connect to your space',
    'account.login.email': 'Email',
    'account.login.emailPlaceholder': 'your@email.com',
    'account.login.password': 'Password',
    'account.login.passwordPlaceholder': '••••••••',
    'account.login.submit': 'Login',
    'account.login.forgot': 'Forgot password?',
    'account.login.noAccount': 'Don\'t have an account?',
    'account.login.register': 'Register',
    'account.login.success': 'Login successful!',
    'account.logout': 'Logout',
    'account.logout.success': 'Logout successful',
    'account.client.orders': 'Orders',
    'account.client.favorites': 'Favorites',
    'account.client.points': 'Loyalty points',
    'account.client.recentOrders': 'Recent orders',
    'account.partenaire.collaborations': 'Collaborations',
    'account.partenaire.revenue': 'Revenue',
    'account.partenaire.products': 'Products',
    'account.partenaire.performance': 'Performance',
    'account.actionnaire.shares': 'Shares',
    'account.actionnaire.value': 'Value',
    'account.actionnaire.dividend': 'Dividend',
    'account.actionnaire.growth': 'Growth',

    'contact.title': 'Contact Us',
    'contact.subtitle': 'We are here to listen to any questions or collaboration opportunities.',
    'contact.info.address.title': 'Address',
    'contact.info.phone.title': 'Phone',
    'contact.info.email.title': 'Email',
    'contact.info.hours.title': 'Hours',
    'contact.info.hours.content': 'Mon - Fri: 8am - 6pm\nSat: 9am - 1pm',
    'contact.social.title': 'Follow us',
    'contact.map.text': 'Find us in the heart of Libreville',
    'contact.map.link': 'View on Google Maps',
    'contact.form.title': 'Send us a message',
    'contact.form.subtitle': 'We will respond as soon as possible.',
    'contact.form.name': 'Name',
    'contact.form.namePlaceholder': 'Your full name',
    'contact.form.email': 'Email',
    'contact.form.emailPlaceholder': 'your@email.com',
    'contact.form.subject': 'Subject',
    'contact.form.subjectPlaceholder': 'Subject of your message',
    'contact.form.message': 'Message',
    'contact.form.messagePlaceholder': 'Your message...',
    'contact.form.submit': 'Send message',
    'contact.form.success': 'Your message has been sent successfully!',

    'footer.description': 'MKH - Mbouma Kohomm: Let\'s transform Africa together through entrepreneurship, education, and excellence.',
    'footer.mkh.mission': 'Our Mission',
    'footer.mkh.portrait': 'Portrait of MK',
    'footer.mkh.history': 'Our History',
    'footer.impact.works': 'Our Works',
    'footer.impact.publications': 'Publications',
    'footer.impact.partners': 'Partners',
    'footer.store.fashion': 'Fashion',
    'footer.store.atrium': 'Atrium',
    'footer.store.new': 'New Arrivals',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.legal.terms': 'Terms of Use',
    'footer.legal.cookies': 'Cookies',
    'footer.rights': 'All rights reserved.',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
